### ISSUE TITLE
<!DOCTYPE html> invalid syntax

### ISSUE THREAD

**Issue by matiascarreno** [parthanium/YoPy#4]
Hi! When I import the ypoy package to my python program and run it, it gives me this error in console:

 `Traceback (most recent call last):

  File "yo.py", line 1, in <module>
    import yopy
  File "/usr/local/lib/python2.7/dist-packages/yopy.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
`
What can I do?

**Comment by matiascarreno** [comment]
My mistake.
